version: "3.4"

services:
  eventstore.db:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
      - EVENTSTORE_DB=/esdb/db
      - EVENTSTORE_LOG=/esdb/log
      - EVENTSTORE_LOG_LEVEL=Verbose
      - EVENTSTORE_NODE_IP=[::]
      - EVENTSTORE_REPLICATION_IP=[::]
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: esdb-volume
        target: /esdb

volumes:
  esdb-volume: