# fly.toml app configuration file generated for eventstoredb on 2024-04-29T18:32:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eventstoredb'
primary_region = 'ewr'

[build]
  image = 'eventstore/eventstore:24.2.0-jammy'

[env]
  EVENTSTORE_CLUSTER_SIZE = '1'
  EVENTSTORE_RUN_PROJECTIONS = 'All'
  EVENTSTORE_START_STANDARD_PROJECTIONS = 'true'
  EVENTSTORE_HTTP_PORT = '2113'
  EVENTSTORE_INSECURE = 'true'
  EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP = 'true'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "myapp_data"
  destination = "/data"