# fly.toml app configuration file generated for armychess-esdb on 2024-05-14T00:29:36-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'armychess-esdb'
primary_region = 'ewr'

[build]
  image = 'eventstore/eventstore:24.2.0-jammy'

[env]
  EVENTSTORE_CLUSTER_SIZE = '1'
  EVENTSTORE_DB = '/esdb/db'
  EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP = 'true'
  EVENTSTORE_HTTP_PORT = '2113'
  EVENTSTORE_INSECURE = 'true'
  EVENTSTORE_LOG = '/esdb/log'
  EVENTSTORE_RUN_PROJECTIONS = 'All'
  EVENTSTORE_START_STANDARD_PROJECTIONS = 'true'
  EVENTSTORE_NODE_IP = '::'
  EVENTSTORE_REPLICATION_IP = '::'

[[mounts]]
  source = 'armychess_esdb_data'
  destination = '/esdb'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
